#!/bin/bash

echo "🚀 L2+ English - Quick Demo Setup"
echo "=================================="
echo ""
echo "✓ Code deployed to: https://l2plus-english-2xxgdz3ow-phoebusdevs-projects.vercel.app"
echo "✓ GitHub repo: https://github.com/phoebusdev/l2plus-english-platform"
echo ""
echo "⏳ Complete these steps in Vercel Dashboard:"
echo ""
echo "1. Create Postgres Database:"
echo "   → Go to https://vercel.com/dashboard"
echo "   → Open 'l2plus-english' project"
echo "   → Storage tab → Create Database → Postgres"
echo ""
echo "2. Add Environment Variable:"
echo "   → Settings → Environment Variables"
echo "   → Add: NEXTAUTH_SECRET"
echo "   → Value: $(openssl rand -base64 32)"
echo ""
echo "3. Add NEXTAUTH_URL:"
echo "   → NEXTAUTH_URL = https://l2plus-english-2xxgdz3ow-phoebusdevs-projects.vercel.app"
echo ""
echo "4. Redeploy:"
echo "   → Deployments → Click latest → Redeploy"
echo ""
echo "5. Run migrations (after DB is created):"
echo "   Run: vercel env pull && npm run db:migrate && npm run db:seed"
echo ""
echo "🎉 Then test your demo!"
echo "   Admin login: admin@l2plusenglish.com / Admin123!"
